#!/usr/bin/env python
import sys
import os

build_commands = {
  "c": "cc -O3 print_primes.c -o print_primes-c -lpthread -lm",
  "c++": "c++ -O3 -std=c++20 print_primes.cpp -o print_primes-c++",
  "java": "javac PrintPrimes.java",
  "rust": "rustc -O print_primes.rs -o print_primes-rust",
  "go": "go build -o print_primes-go print_primes.go"
}

if len(sys.argv) < 2 or sys.argv[1] not in build_commands:
   print(f"usage: {sys.argv[0]} {{ c | c++ | java | rust | go }}",
   	 file=sys.stderr)
   exit(1)

command = build_commands[sys.argv[1]]
print("Building:", command)
os.system(command)



